export const ROUTE_NAMES = {
    login: "/",
    dashboard: "/dashboard",
    reportOrders: "/reportOrders",
      reportOrdersByStore: "/reportOrdersByStore",
      reportInventoryByProduct: "/reportInventoryByProduct",
      reportInventoryByStore: "/reportInventoryByStore",
      reportProductsByPopularity: "/reportProductsByPopularity",
      reportsTemperature: "/reportsTemperature",
      reportsSensor: "/reportsSensor",
      reportTemperaturesByStore: "/reportTemperaturesByStore",
    orders: "/orders",
      orderView: "/orderView",
    mobileOrders: "/mobileOrders",
      mobileOrderView: "/mobileOrderView",
    products: "/definedProducts",
      productItems: "/allInventory",
      productView: "/definedProductView",
      productItemView: "/allInventoryView",
      categories: "/categories",
      categoryView: "/categoryView",
      tags: "/tags",
      tagView: "/tagView",
      metrics: "/variations",
      metricView: "/variationView",
      controls: "/controls",
      controlView: "/controlView",
      taxes: "/taxes",
      taxView: "/taxView",
      bundleView: "/bundleView",
    customers: "/customers",
      customerView: "/customerView",
    mobileUsers: "/mobileCustomers",
      mobileUserView: "/mobileCustomerView",
    kiosks: "/kiosks",
      kioskView: "/kioskView",
    machines: "/machines",
      machineView: "/machineView",
    stores: "/stores",
      storeView: "/storeView",
    users: "/users",
      userView: "/userView",
      usersTypesView: "/userTypesView",
    cookingTips: "/cookingTips",
      cookingTipsView: "/cookingTipsView",
    alarms: "/alarms",
      alarmsView: "/alarmsView",
    carousel: "/carousel",
    logs: "/logs",
      logsView: "/logsView",
    helpView: "/helpView",
    emails: "/emails",
      emailView: "/emailView",

    statusesOrders: "/statusesOrders",
      statusesOrdersView: "/statusesOrdersView",
    statusesProducts: "/statusesProducts",
      statusesProductsView: "/statusesProductsView",
    statusesProductItems: "/statusesProductItems",
      statusesProductItemsView: "/statusesProductItemsView",
    statusesStores: "/statusesStores",
      statusesStoresView: "/statusesStoresView",
    statusesMachines: "/statusesMachines",
      statusesMachinesView: "/statusesMachinesView",
    statusesKiosks: "/statusesKiosks",
      statusesKiosksView: "/statusesKiosksView",
    statusesCustomers: "/statusesCustomers",
      statusesCustomersView: "/statusesCustomersView",

    rolesAdmins: "/rolesAdmins",
      rolesAdminsView: "/rolesAdminsView",
  
    couponsGenerator: "/couponsGenerator",
    promotions: "/promotions",
    promotionView: "/promotionView",

    sleepScreenView: "/sleepScreenView",
    visualIdentityView: "/visualIdentityView"
};

export const QUERY_PARAMS = {
  itemId: "itemId",
};

export const QUERY_VALUES = {
};
